---
deployment:
  tasks:
    - export DEPLOYPATH=/home/musephx3r/public_html/templates/sephirot/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -av --delete --exclude '.git' --exclude '.cpanel.yml' --exclude 'node_modules' ./ $DEPLOYPATH
