---
deployment:
  tasks:
    - export DEPLOYPATH=/home/musephx3r/public_html/templates/sephirot/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "${DEPLOYPATH:?}"*
    - /bin/tar -cf - . --exclude='.git' --exclude='node_modules' --exclude='.cpanel.yml' | /bin/tar -xf - -C "$DEPLOYPATH"

    # Fix permisos
    - /bin/chmod -R 755 "$DEPLOYPATH"
    - /usr/bin/find "$DEPLOYPATH" -type f -exec /bin/chmod 644 {} \;
